### ISSUE TITLE
Support for additional filters

### ISSUE THREAD

**Issue by atifazad** [k8spin/prometheus-multi-tenant-proxy#51]
Currenty, the proxy only adds a filter for the `namespace` label, which is well suited to filter by k8s namespaces. This issue is about adding support for additional/customizable filters on top/instead of namespaces.

We would like to restrict access to metrics at (for example) the application level instead of the namespace.

In this case, the configuration could look like this:

```
  - username: Different labels
    password: NamespacesWithoutAppName
    labels:
      namespace: default
      app_name: poll-demo-app
```

**Comment by derlin** [comment]
Another cool thing would be to be able to change the default filter. This proxy may be used in other, non-kubernetes contexts where the namespace doesn't exist.

**Comment by angelbarrera92** [comment]
It could make sense, let me double check it and review this option :)

**Comment by angelbarrera92** [comment]
> Another cool thing would be to be able to change the default filter. This proxy may be used in other, non-kubernetes contexts where the namespace doesn't exist.

I think you are describing exactly what @atifazad is saying, right?



> Currenty, the proxy only adds a filter for the `namespace` label, which is well suited to filter by k8s namespaces. This issue is about adding support for additional/customizable filters on top/instead of namespaces.
> 
> We would like to restrict access to metrics at (for example) the application level instead of the namespace.
> 
> In this case, the configuration could look like this:
> 
> ```
>   - username: Different labels
>     password: NamespacesWithoutAppName
>     labels:
>       namespace: default
>       app_name: poll-demo-app
> ```

It could be a good idea, let's think about a non-breaking way of implementing it.

What about:

- If config file does not contain `labels`; `namespace` will be injected anyway.
- If config file does contain both `labels` and `namespace/s`, both will be applied.
- If config file does contain `labels` but not `namespace`, labels will be injected.
- At least one of `labels` or `namespace/s` must be present.


Examples:

```yaml
users:
  - username: Happy
    password: Prometheus
    namespace: default
```
Will inject: `namespace="default"`

---------

```yaml
users:
  - username: Happy
    password: Prometheus
    namespaces: 
    - default
    - kube-system
```

Will inject: `namespace="default|kube-system"`

---------

```yaml
users:
  - username: Happy
    password: Prometheus
    labels: 
      team: A
```

Will inject: `team="A"`

---------

```yaml
users:
  - username: Happy
    password: Prometheus
    namespace: default
    labels: 
      team: A
```

Will inject: `team="A",namespace="default"`

---------

```yaml
users:
  - username: Happy
    password: Prometheus
    namespace: default
    namespaces:
      - teama
      - monitoring
    labels: 
      team: A
```

Will inject: `team="A",namespace="default|teama|monitoring"`

---------

```yaml
users:
  - username: Happy
    password: Prometheus
```

**Incorrect**

---------

I think it does make sense, what do you think?
